#Building with Msys2 on Appvoyer
version: 1.3.0-Alpha.{build}

clone_depth: 50

environment:
  matrix:
    - MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64
    - MSYS2_ARCH: i686
      MSYSTEM: MINGW32

install:
  - PATH C:\msys64\%MSYSTEM%\bin;C:\msys64\usr\bin;C:\msys64\bin;%PATH%
  - bash %APPVEYOR_BUILD_FOLDER%\windows\msys2-build.sh installdeps

build_script:
  - bash %APPVEYOR_BUILD_FOLDER%\windows\msys2-build.sh build

test_script:
  - bash %APPVEYOR_BUILD_FOLDER%\windows\msys2-build.sh test
