language: cpp
compiler:
    - gcc

sudo: false

addons:
  apt:
    packages:
      - g++
      - gettext
      - gir1.2-gtk-3.0
      - libgtk-3-dev
      - libjson0-dev
      - liblcms2-dev
      - libpng12-dev
      - python-dev
      - python-gi-dev
      - python-gi-cairo
      - python-nose
      - python-numpy
      - scons
      - swig

script:
    - scons
    - nosetests --with-doctest lib brushlib
